import "./globals.css";
import { MarkBold, MarkMedium, MarkRegular } from "./fonts";
import type { Metadata } from "next";

import { Providers } from "./providers";
import Header from "@/components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${MarkRegular.variable} ${MarkMedium.variable} ${MarkBold.variable}`}
      >
        <Providers>
          <Header />

          {children}
        </Providers>
      </body>
    </html>
  );
}
